Add pending status and new API entry for task status update
farao-community/gridcapa-task-manager pull request #31
Opened 2022-04-21 11:45 UTC by TheMaskedTurtle

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
New task status PENDING in between ready and running. I also aded a fix on task manager handling of messages. Concurrent access to the database could lead to wrong behavior.

2022-04-22 07:28 UTC, murgeyseb requested changes

2022-04-22 07:28 UTC, murgeyseb commented on gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
> +        synchronized (LOCK) {
Perhaps you could mutualize code for the inner part of both handleTaskStatusUpdate methods

2022-05-13 15:28 UTC, benrejebmoh approved these changes

2022-05-16 09:14 UTC, benrejebmoh approved these changes

2022-05-16 09:16 UTC, benrejebmoh approved these changes

2022-05-16 09:17 UTC, merged