Now save object key and no more presigned url in database
farao-community/gridcapa-task-manager pull request #58
Opened 2023-01-25 13:46 UTC by TheoPascoli

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-02-01 15:51 UTC, schwitzguebel approved these changes

2023-02-02 13:41 UTC, schwitzguebel submitted a review, later dismissed

2023-02-03 14:41 UTC, WalAmeni requested changes

2023-02-03 14:41 UTC, WalAmeni commented on gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
> +            ProcessFile processFile = new ProcessFile(objectKey, fileGroup, fileType, startTime, endTime, objectKey, getProcessNow());
objectKey is already saved in the processsFile constructor

2023-02-03 14:41 UTC, WalAmeni commented on gridcapa-task-manager-app/src/main/java/com/farao_community/farao/gridcapa/task_manager/app/TaskManager.java
> +            processFile.setFileUrl(objectKey);
You are setting the same value object key in two different variables

2023-02-08 10:52 UTC, WalAmeni approved these changes

2023-02-08 10:52 UTC, merged